In [1]:
from kaggle_environments import make
from scipy.stats import norm

import hyperopt
import numpy as np
import os
if not os.path.exists('tmp'):
    os.mkdir('tmp')
    
base_path = '/Users/sergmiller/Documents/my/bandits'

Loading environment football failed: No module named 'gfootball'


In [2]:
from utils.bandits import Agent, init_agent, \
    compare, gittins_bb_delta, init_template, gittins_with_random, bench

In [95]:
from importlib import reload
import utils
reload(utils)
reload(utils.bandits)
from utils.bandits import exact_gittins

In [4]:
compare(Agent(text=utils.bandits.exact_gittins), Agent(text=gittins_with_random))

(0.004648520752065718,
 24.5,
 27.37243138634199,
 array([656., 634., 666., 634., 579., 717., 657., 650., 572., 572.]),
 array([611., 647., 619., 589., 524., 684., 629., 612., 598., 579.]))

In [7]:
compare(
    Agent(text=utils.bandits.exact_gittins_with_my_and_count_rival_drift.format("decay=0.03")),
    Agent(text=gittins_with_random)
)

(2.3276030960020468e-08,
 27.9,
 15.795252451290546,
 array([720., 583., 663., 641., 551., 640., 678., 653., 659., 673.]),
 array([699., 551., 641., 610., 520., 649., 661., 614., 610., 627.]))

In [12]:
compare(
    Agent(text=utils.bandits.exact_gittins_with_my_and_count_rival_drift.format("decay=0.03")),
    Agent(file='/Users/sergmiller/Documents/my/bandits/kernels/thompson.py'), T=50
)

(0.1764349031503316,
 -5.38,
 28.141705705234003,
 array([716., 667., 629., 678., 704., 651., 629., 566., 598., 648., 635.,
        634., 624., 570., 598., 614., 660., 659., 628., 642., 611., 603.,
        617., 580., 669., 642., 650., 725., 578., 619., 587., 587., 613.,
        667., 676., 638., 586., 560., 619., 626., 682., 594., 622., 622.,
        634., 602., 613., 646., 647., 630.]),
 array([707., 629., 626., 691., 728., 654., 638., 565., 604., 637., 626.,
        662., 580., 586., 592., 625., 668., 703., 668., 692., 573., 611.,
        683., 626., 658., 628., 629., 755., 619., 643., 635., 642., 626.,
        629., 688., 632., 599., 573., 610., 595., 650., 595., 601., 676.,
        664., 552., 585., 634., 651., 621.]))

In [8]:
compare(
    Agent(text=neural),
    Agent(file='/Users/sergmiller/Documents/my/bandits/kernels/thompson.py')
)

(0.02917153861564571,
 18.4,
 26.6765814901385,
 array([634., 641., 680., 660., 669., 633., 628., 606., 677., 620.]),
 array([615., 618., 641., 604., 610., 622., 659., 608., 685., 602.]))

In [9]:
compare(
    Agent(text=utils.bandits.exact_gittins_with_my_and_count_rival_drift.format("decay=0.03")),
    Agent(text=neural)
)

(0.07425523842219167,
 12.1,
 21.43571785595248,
 array([641., 582., 639., 584., 592., 620., 655., 605., 670., 619.]),
 array([628., 584., 626., 576., 630., 572., 639., 598., 638., 595.]))

In [15]:
a = Agent(text=utils.bandits.exact_gittins_with_my_and_count_rival_drift)
init_agent(a)
a.file

'tmp/b_0.5812310031940234.py'

In [16]:
bench(a)

['gittins', (0.020986698049977895, 14.3, 19.59106939398664)]
['gittins_with_random', (0.15807235983080392, 11.9, 26.658769664033635)]
['gittins_with_count_my', (0.6660084920493266, -3.7, 27.10737906917598)]
['gittins_with_count_rival_drift', (0.01869799440970269, 30.1, 40.47826577312818)]
['gittins_with_my_and_count_rival_drift', (0.9580712014743338, 0.3, 18.044666802132976)]
['gittins_bb', (0.007737945727551424, 23.1, 27.427905497868405)]
['gittins_bb_delta', (0.5962530712266272, -3.9, 23.278530881479615)]
['softmax_ucb', (0.0001271960961194171, 26.0, 21.45693361130616)]
['multiarmed_bandit_agent', (0.17846353458821285, 13.4, 31.493491391079523)]
['upper_confidence', (5.82610972839857e-17, 114.2, 43.15275194005592)]
['ucb_decay', (0.5051202363556915, 7.0, 33.214454684670045)]
['bayesian_ucb', (0.0018612734514125444, -23.0, 23.375200533899168)]
['thompson', (0.10523248484614844, -11.8, 23.03388807822075)]
['neural', (0.3706954653292832, -9.5, 33.55964838909967)]
<string>:82: RuntimeWar

[['gittins', (0.020986698049977895, 14.3, 19.59106939398664)],
 ['gittins_with_random', (0.15807235983080392, 11.9, 26.658769664033635)],
 ['gittins_with_count_my', (0.6660084920493266, -3.7, 27.10737906917598)],
 ['gittins_with_count_rival_drift',
  (0.01869799440970269, 30.1, 40.47826577312818)],
 ['gittins_with_my_and_count_rival_drift',
  (0.9580712014743338, 0.3, 18.044666802132976)],
 ['gittins_bb', (0.007737945727551424, 23.1, 27.427905497868405)],
 ['gittins_bb_delta', (0.5962530712266272, -3.9, 23.278530881479615)],
 ['softmax_ucb', (0.0001271960961194171, 26.0, 21.45693361130616)],
 ['multiarmed_bandit_agent', (0.17846353458821285, 13.4, 31.493491391079523)],
 ['upper_confidence', (5.82610972839857e-17, 114.2, 43.15275194005592)],
 ['ucb_decay', (0.5051202363556915, 7.0, 33.214454684670045)],
 ['bayesian_ucb', (0.0018612734514125444, -23.0, 23.375200533899168)],
 ['thompson', (0.10523248484614844, -11.8, 23.03388807822075)],
 ['neural', (0.3706954653292832, -9.5, 33.559648389

In [ ]:
a = Agent(text=utils.bandits.exact_gittins_with_my_and_count_rival_drift.format("decay=0.03"))
init_agent(a)
a.file

bench(a)

In [20]:
a = Agent(text=utils.bandits.exact_gittins_with_my_and_count_rival_drift.format("decay,rival_drift=0.03,-0.001"))
init_agent(a)
print(a.file)

bench(a)

tmp/b_0.6698981319746636.py
['gittins', (0.0070556045568421835, 23.7, 27.817440572417873)]
['gittins_with_random', (0.04412062421763874, 27.1, 42.57334847061011)]
['gittins_with_count_my', (0.25099289960537385, -9.7, 26.720965551416736)]
['gittins_with_count_rival_drift', (0.04259029267837131, 25.7, 40.08004491015448)]
['gittins_with_my_and_count_rival_drift', (0.5166336434853575, -3.4, 16.578299068360423)]
['gittins_bb', (0.5320094981546408, -4.7, 23.782556632961054)]
['gittins_bb_delta', (0.002768822035859739, -19.3, 20.39632319806685)]
['softmax_ucb', (0.04150945267886, 19.7, 30.56157718443209)]
['multiarmed_bandit_agent', (0.17437960669542285, -12.4, 28.86936092122581)]
['upper_confidence', (3.467615329731626e-31, 108.4, 29.513386793114748)]
['ucb_decay', (0.0005200056109070572, 14.1, 12.848735346328837)]
['bayesian_ucb', (0.009494949012238142, -27.1, 33.04073243740217)]
['thompson', (0.005615350124280827, -24.0, 27.40437921208944)]
['neural', (0.0024994871875276574, -23.9, 24.9977

[['gittins', (0.0070556045568421835, 23.7, 27.817440572417873)],
 ['gittins_with_random', (0.04412062421763874, 27.1, 42.57334847061011)],
 ['gittins_with_count_my', (0.25099289960537385, -9.7, 26.720965551416736)],
 ['gittins_with_count_rival_drift',
  (0.04259029267837131, 25.7, 40.08004491015448)],
 ['gittins_with_my_and_count_rival_drift',
  (0.5166336434853575, -3.4, 16.578299068360423)],
 ['gittins_bb', (0.5320094981546408, -4.7, 23.782556632961054)],
 ['gittins_bb_delta', (0.002768822035859739, -19.3, 20.39632319806685)],
 ['softmax_ucb', (0.04150945267886, 19.7, 30.56157718443209)],
 ['multiarmed_bandit_agent', (0.17437960669542285, -12.4, 28.86936092122581)],
 ['upper_confidence', (3.467615329731626e-31, 108.4, 29.513386793114748)],
 ['ucb_decay', (0.0005200056109070572, 14.1, 12.848735346328837)],
 ['bayesian_ucb', (0.009494949012238142, -27.1, 33.04073243740217)],
 ['thompson', (0.005615350124280827, -24.0, 27.40437921208944)],
 ['neural', (0.0024994871875276574, -23.9, 24.9

In [44]:
compare(
    Agent(file='/Users/sergmiller/Documents/my/bandits/kernels/thompson.py'),
    Agent(text=neural),
    T=20
)

(0.9332597025183905,
 -0.5,
 26.701123571864912,
 array([604., 633., 672., 631., 641., 651., 570., 580., 654., 644., 552.,
        646., 705., 635., 699., 582., 591., 599., 600., 614.]),
 array([650., 653., 675., 646., 576., 636., 572., 591., 646., 649., 594.,
        619., 673., 632., 713., 632., 578., 588., 583., 607.]))

In [47]:
a = Agent(text=utils.bandits.neural_with_new_feature)
init_agent(a)
print(a.file)

compare(
    a,
    Agent(text=neural),
    T=10
)

tmp/b_0.23472610887543255.py


(0.3305564893681603,
 10.3,
 33.47551343893025,
 array([673., 612., 620., 627., 619., 636., 621., 652., 700., 603.]),
 array([662., 649., 576., 633., 640., 585., 605., 601., 665., 644.]))

In [48]:
bench(a)

['gittins', (1.6938640196923583e-10, 40.9, 20.25067900096192)]
['gittins_with_random', (0.052672869607180664, 26.3, 42.923303693914335)]
['gittins_with_count_my', (0.03200258150073675, 12.9, 19.02340663498523)]
['gittins_with_count_rival_drift', (6.017970810148189e-06, 30.0, 20.961870145576228)]
['gittins_with_my_and_count_rival_drift', (0.0008999073004778537, 23.1, 22.002045359466017)]
['gittins_bb', (0.40613713755483416, 5.6, 21.317598363793234)]
['gittins_bb_delta', (0.9581997736625133, 0.5, 30.16703498854337)]
['softmax_ucb', (1.0467690209347524e-05, 31.9, 22.88864347225497)]
['multiarmed_bandit_agent', (0.0709880063216172, 16.8, 29.42379989056478)]
['upper_confidence', (1.9599021635144304e-179, 145.7, 16.131026005806326)]
['ucb_decay', (0.00020299463049364502, 29.1, 24.768730286391346)]
['bayesian_ucb', (0.2935579760577147, -6.6, 19.87058126980688)]
['thompson', (0.8865350313680469, 1.1, 24.37806390999909)]
['neural', (0.3520256594239479, -5.5, 18.688231591030757)]
<string>:82: Ru

[['gittins', (1.6938640196923583e-10, 40.9, 20.25067900096192)],
 ['gittins_with_random', (0.052672869607180664, 26.3, 42.923303693914335)],
 ['gittins_with_count_my', (0.03200258150073675, 12.9, 19.02340663498523)],
 ['gittins_with_count_rival_drift',
  (6.017970810148189e-06, 30.0, 20.961870145576228)],
 ['gittins_with_my_and_count_rival_drift',
  (0.0008999073004778537, 23.1, 22.002045359466017)],
 ['gittins_bb', (0.40613713755483416, 5.6, 21.317598363793234)],
 ['gittins_bb_delta', (0.9581997736625133, 0.5, 30.16703498854337)],
 ['softmax_ucb', (1.0467690209347524e-05, 31.9, 22.88864347225497)],
 ['multiarmed_bandit_agent', (0.0709880063216172, 16.8, 29.42379989056478)],
 ['upper_confidence', (1.9599021635144304e-179, 145.7, 16.131026005806326)],
 ['ucb_decay', (0.00020299463049364502, 29.1, 24.768730286391346)],
 ['bayesian_ucb', (0.2935579760577147, -6.6, 19.87058126980688)],
 ['thompson', (0.8865350313680469, 1.1, 24.37806390999909)],
 ['neural', (0.3520256594239479, -5.5, 18.68

In [52]:
a = Agent(text=utils.bandits.neural.format("", "baseline = thompson"))
init_agent(a)
print(a.file)

compare(
    a,
    Agent(text=neural),
    T=20
)

tmp/b_0.007705609680770942.py


(0.6305495981081255,
 -2.8,
 26.0357446599862,
 array([591., 604., 606., 588., 583., 575., 608., 663., 606., 613., 579.,
        682., 639., 593., 534., 675., 638., 649., 661., 634.]),
 array([626., 611., 624., 567., 534., 596., 626., 651., 615., 591., 592.,
        735., 663., 617., 566., 658., 607., 649., 625., 624.]))

In [53]:
a = Agent(text=utils.bandits.neural.format("", "baseline = exact_gittins"))
init_agent(a)
print(a.file)

compare(
    a,
    Agent(text=neural),
    T=20
)

tmp/b_0.3044403776073804.py


(0.9713881701041046,
 0.2,
 24.93712092443713,
 array([622., 644., 586., 642., 639., 625., 629., 606., 675., 617., 665.,
        596., 566., 644., 633., 618., 572., 664., 595., 610.]),
 array([640., 687., 570., 635., 677., 632., 637., 613., 670., 632., 617.,
        594., 549., 597., 619., 604., 615., 634., 601., 621.]))

In [54]:
bench(Agent(file='tmp/b_0.007705609680770942.py'))

['gittins', (1.3482278820124438e-05, 32.3, 23.469341703592796)]
['gittins_with_random', (0.0014739156930801886, 27.8, 27.64706132665821)]
['gittins_with_count_my', (0.2136831927385785, 10.6, 26.956260868302934)]
['gittins_with_count_rival_drift', (8.29899312396653e-05, 25.9, 20.81081449631417)]
['gittins_with_my_and_count_rival_drift', (0.121311388580548, 7.7, 15.7165517846632)]
['gittins_bb', (0.34724589261984773, 5.8, 19.513072541247826)]
['gittins_bb_delta', (2.587106889569581e-05, 18.3, 13.755362590640786)]
['softmax_ucb', (2.1965722857185216e-07, 46.5, 28.376927247325423)]
['multiarmed_bandit_agent', (0.6320934299942775, -3.7, 24.437880431821412)]
['upper_confidence', (8.884324421771018e-34, 139.8, 36.49328705392267)]
['ucb_decay', (0.00014036633178158772, 34.8, 28.902595039200197)]
['bayesian_ucb', (0.36864533480594686, -7.8, 27.436472076416823)]
['thompson', (0.067679223272783, 15.5, 26.82629307228265)]
['neural', (0.12006680285692949, -15.4, 31.327942798722038)]
<string>:82: Ru

[['gittins', (1.3482278820124438e-05, 32.3, 23.469341703592796)],
 ['gittins_with_random', (0.0014739156930801886, 27.8, 27.64706132665821)],
 ['gittins_with_count_my', (0.2136831927385785, 10.6, 26.956260868302934)],
 ['gittins_with_count_rival_drift',
  (8.29899312396653e-05, 25.9, 20.81081449631417)],
 ['gittins_with_my_and_count_rival_drift',
  (0.121311388580548, 7.7, 15.7165517846632)],
 ['gittins_bb', (0.34724589261984773, 5.8, 19.513072541247826)],
 ['gittins_bb_delta', (2.587106889569581e-05, 18.3, 13.755362590640786)],
 ['softmax_ucb', (2.1965722857185216e-07, 46.5, 28.376927247325423)],
 ['multiarmed_bandit_agent', (0.6320934299942775, -3.7, 24.437880431821412)],
 ['upper_confidence', (8.884324421771018e-34, 139.8, 36.49328705392267)],
 ['ucb_decay', (0.00014036633178158772, 34.8, 28.902595039200197)],
 ['bayesian_ucb', (0.36864533480594686, -7.8, 27.436472076416823)],
 ['thompson', (0.067679223272783, 15.5, 26.82629307228265)],
 ['neural', (0.12006680285692949, -15.4, 31.32

In [56]:
a = Agent(text=utils.bandits.neural_with_new_feature.format("", "bucb"))
init_agent(a)
print(a.file)

compare(
    a,
    Agent(text=neural),
    T=20
)

tmp/b_0.33959486832463204.py


(0.6257020448138657,
 -3.35,
 30.71363703633941,
 array([606., 678., 660., 605., 593., 619., 585., 588., 625., 627., 600.,
        596., 605., 647., 655., 606., 566., 663., 709., 650.]),
 array([562., 642., 671., 616., 592., 627., 652., 620., 644., 662., 614.,
        621., 638., 610., 685., 579., 582., 634., 661., 638.]))

In [58]:
compare(
    a,
    Agent(file='/Users/sergmiller/Documents/my/bandits/kernels/bayesian_ucb.py'),
    T=10
)

(0.002198943481250541,
 -35.2,
 36.353266703282664,
 array([591., 567., 647., 650., 615., 519., 582., 594., 617., 620.]),
 array([641., 627., 704., 592., 649., 584., 656., 620., 653., 628.]))

In [61]:
compare(
    Agent(text=neural),
    Agent(file='/Users/sergmiller/Documents/my/bandits/kernels/bayesian_ucb.py'),
    T=10
)

(0.08647270751665442,
 15.2,
 28.038544898050613,
 array([598., 554., 630., 633., 667., 582., 611., 630., 665., 662.]),
 array([616., 536., 674., 608., 640., 566., 583., 597., 601., 659.]))

In [71]:
compare(
    Agent(text=utils.bandits.neural),
    Agent(file='/Users/sergmiller/Documents/my/bandits/kernels/bayesian_ucb.py'),
    T=20
)

(0.7749767666710601,
 -2.35,
 36.76312690726946,
 array([608., 706., 600., 657., 620., 654., 600., 644., 553., 622., 598.,
        683., 641., 553., 675., 554., 675., 646., 600., 569.]),
 array([642., 659., 611., 666., 595., 604., 583., 648., 503., 673., 583.,
        701., 592., 608., 632., 616., 697., 653., 649., 590.]))

In [77]:
# remove bias decay before loss
compare(
    Agent(text=utils.bandits.neural),
    Agent(file='/Users/sergmiller/Documents/my/bandits/kernels/bayesian_ucb.py'),
    T=20
)

(0.674196059985329,
 -3.45,
 36.70078337038598,
 array([614., 648., 654., 628., 576., 617., 677., 637., 621., 706., 588.,
        646., 697., 605., 604., 667., 651., 644., 658., 639.]),
 array([614., 645., 609., 603., 613., 625., 705., 630., 609., 643., 650.,
        628., 650., 654., 647., 633., 634., 713., 693., 648.]))

In [89]:
compare(
    Agent(text=utils.bandits.neural),
    Agent(file='/Users/sergmiller/Documents/my/bandits/kernels/bayesian_ucb.py'),
    T=10
)

(0.8562035082524957,
 -1.1,
 19.196093352554836,
 array([630., 567., 704., 546., 620., 659., 649., 599., 678., 591.]),
 array([647., 567., 705., 571., 584., 689., 639., 586., 664., 602.]))

In [96]:
compare(
    Agent(text=utils.bandits.neural),
    Agent(file=utils.bandits.neural.format("top_negatives,negatives_weight=1,0", "")),
    T=10
)

(0.36280557914975653,
 6.9,
 23.97686384830176,
 array([638., 564., 684., 687., 674., 710., 656., 597., 620., 604.]),
 array([641., 587., 664., 675., 625., 684., 647., 621., 645., 576.]))

In [98]:
compare(
    Agent(text=utils.bandits.neural),
    Agent(file=utils.bandits.neural.format("top_negatives,negatives_weight=1,0.1", "")),
    T=20
)

(0.25987824293310424,
 8.95,
 35.525307880439264,
 array([616., 608., 643., 577., 624., 658., 621., 682., 657., 674., 641.,
        592., 585., 641., 615., 590., 662., 649., 703., 655.]),
 array([594., 595., 645., 565., 616., 580., 633., 653., 696., 703., 583.,
        591., 642., 625., 627., 542., 719., 599., 669., 637.]))

In [99]:
compare(
    Agent(text=utils.bandits.neural),
    Agent(file=utils.bandits.neural.format("top_negatives,negatives_weight=5,0.1", "")),
    T=20
)

(0.3496656734725794,
 -6.2,
 29.64725956981522,
 array([636., 673., 677., 586., 659., 631., 688., 554., 603., 643., 602.,
        576., 665., 537., 672., 604., 608., 570., 557., 596.]),
 array([651., 673., 669., 632., 655., 635., 676., 570., 563., 594., 642.,
        615., 660., 523., 663., 670., 639., 597., 517., 617.]))

In [126]:
def f_neural(input):
    #input['hidden'] = int(input['hidden'])
    print(input)
    neural_custom = init_template(utils.bandits.neural.format("{}",""), input)
    res = compare(Agent(text=utils.bandits.neural), Agent(text=neural_custom), T=10)[:3]
    f_out = lambda mu, sigma: (mu + sigma) * ( 1 + (mu >= 0)) # since expect mu < 0
    score = f_out(res[1], res[2])
    print(score, res)
    return score

In [127]:
search_space = {
  "lr": hyperopt.hp.loguniform('lr', np.log(1e-3), np.log(1e-2)),
  "top_negatives": hyperopt.hp.randint("top_negatives", 10, 25),
  "negatives_weight": hyperopt.hp.loguniform("negatives_weight", np.log(1e-9), np.log(25)),
}

trials = hyperopt.Trials()
best = hyperopt.fmin(
  fn=f_neural,
  space=search_space,
  algo=hyperopt.tpe.suggest,
  max_evals=250,
  verbose=True,
  trials=trials)
print(best)


{'lr': 0.008070103624278242, 'negatives_weight': 2.226651317111342e-05, 'top_negatives': 19}
153.7463294677202                                      
(0.0030253923130460153, 37.2, 39.67316473386009)       
{'lr': 0.006113891873304902, 'negatives_weight': 1.6567316911061993e-06, 'top_negatives': 18}
27.01797299117399                                                                 
(0.4451440814278852, -8.6, 35.61797299117399)                                     
{'lr': 0.005887292915219309, 'negatives_weight': 2.003907865494522e-06, 'top_negatives': 14}
114.22571776442625                                                                
(0.03981814855025607, 22.5, 34.612858882213125)                                   
{'lr': 0.0019209165876168416, 'negatives_weight': 0.12996532884746234, 'top_negatives': 16}
75.84543940806594                                                                 
(0.7247183141362814, 3.8, 34.122719704032974)                                     
{'lr': 0.005446153

In [ ]:
(0.0023010486487075356, -25.9, 26.868010719068874)                                  
{'lr': 0.0050905177685504404, 'negatives_weight': 23.294897815416206, 'top_negatives': 21}
95.08388856004842

{'lr': 0.0010024617680657114, 'negatives_weight': 4.9775458673981656e-08, 'top_negatives': 24}
-19.1                                                                    
(0.010098781780592413, -19.1, 23.479565583715555)     