In [1]:
from kaggle_environments import make
from scipy.stats import norm

import hyperopt
import numpy as np
import os
if not os.path.exists('tmp'):
    os.mkdir('tmp')
    
base_path = '/Users/sergmiller/Documents/my/bandits'

Loading environment football failed: No module named 'gfootball'


In [2]:
from utils.bandits import Agent, init_agent, \
    compare, gittins_bb_delta, init_template, neural, gittins_with_random, bench

In [46]:
from importlib import reload
import utils
reload(utils)
reload(utils.bandits)
from utils.bandits import exact_gittins

In [4]:
compare(Agent(text=utils.bandits.exact_gittins), Agent(text=gittins_with_random))

(0.004648520752065718,
 24.5,
 27.37243138634199,
 array([656., 634., 666., 634., 579., 717., 657., 650., 572., 572.]),
 array([611., 647., 619., 589., 524., 684., 629., 612., 598., 579.]))

In [7]:
compare(
    Agent(text=utils.bandits.exact_gittins_with_my_and_count_rival_drift.format("decay=0.03")),
    Agent(text=gittins_with_random)
)

(2.3276030960020468e-08,
 27.9,
 15.795252451290546,
 array([720., 583., 663., 641., 551., 640., 678., 653., 659., 673.]),
 array([699., 551., 641., 610., 520., 649., 661., 614., 610., 627.]))

In [12]:
compare(
    Agent(text=utils.bandits.exact_gittins_with_my_and_count_rival_drift.format("decay=0.03")),
    Agent(file='/Users/sergmiller/Documents/my/bandits/kernels/thompson.py'), T=50
)

(0.1764349031503316,
 -5.38,
 28.141705705234003,
 array([716., 667., 629., 678., 704., 651., 629., 566., 598., 648., 635.,
        634., 624., 570., 598., 614., 660., 659., 628., 642., 611., 603.,
        617., 580., 669., 642., 650., 725., 578., 619., 587., 587., 613.,
        667., 676., 638., 586., 560., 619., 626., 682., 594., 622., 622.,
        634., 602., 613., 646., 647., 630.]),
 array([707., 629., 626., 691., 728., 654., 638., 565., 604., 637., 626.,
        662., 580., 586., 592., 625., 668., 703., 668., 692., 573., 611.,
        683., 626., 658., 628., 629., 755., 619., 643., 635., 642., 626.,
        629., 688., 632., 599., 573., 610., 595., 650., 595., 601., 676.,
        664., 552., 585., 634., 651., 621.]))

In [8]:
compare(
    Agent(text=neural),
    Agent(file='/Users/sergmiller/Documents/my/bandits/kernels/thompson.py')
)

(0.02917153861564571,
 18.4,
 26.6765814901385,
 array([634., 641., 680., 660., 669., 633., 628., 606., 677., 620.]),
 array([615., 618., 641., 604., 610., 622., 659., 608., 685., 602.]))

In [9]:
compare(
    Agent(text=utils.bandits.exact_gittins_with_my_and_count_rival_drift.format("decay=0.03")),
    Agent(text=neural)
)

(0.07425523842219167,
 12.1,
 21.43571785595248,
 array([641., 582., 639., 584., 592., 620., 655., 605., 670., 619.]),
 array([628., 584., 626., 576., 630., 572., 639., 598., 638., 595.]))

In [15]:
a = Agent(text=utils.bandits.exact_gittins_with_my_and_count_rival_drift)
init_agent(a)
a.file

'tmp/b_0.5812310031940234.py'

In [16]:
bench(a)

['gittins', (0.020986698049977895, 14.3, 19.59106939398664)]
['gittins_with_random', (0.15807235983080392, 11.9, 26.658769664033635)]
['gittins_with_count_my', (0.6660084920493266, -3.7, 27.10737906917598)]
['gittins_with_count_rival_drift', (0.01869799440970269, 30.1, 40.47826577312818)]
['gittins_with_my_and_count_rival_drift', (0.9580712014743338, 0.3, 18.044666802132976)]
['gittins_bb', (0.007737945727551424, 23.1, 27.427905497868405)]
['gittins_bb_delta', (0.5962530712266272, -3.9, 23.278530881479615)]
['softmax_ucb', (0.0001271960961194171, 26.0, 21.45693361130616)]
['multiarmed_bandit_agent', (0.17846353458821285, 13.4, 31.493491391079523)]
['upper_confidence', (5.82610972839857e-17, 114.2, 43.15275194005592)]
['ucb_decay', (0.5051202363556915, 7.0, 33.214454684670045)]
['bayesian_ucb', (0.0018612734514125444, -23.0, 23.375200533899168)]
['thompson', (0.10523248484614844, -11.8, 23.03388807822075)]
['neural', (0.3706954653292832, -9.5, 33.55964838909967)]
<string>:82: RuntimeWar

[['gittins', (0.020986698049977895, 14.3, 19.59106939398664)],
 ['gittins_with_random', (0.15807235983080392, 11.9, 26.658769664033635)],
 ['gittins_with_count_my', (0.6660084920493266, -3.7, 27.10737906917598)],
 ['gittins_with_count_rival_drift',
  (0.01869799440970269, 30.1, 40.47826577312818)],
 ['gittins_with_my_and_count_rival_drift',
  (0.9580712014743338, 0.3, 18.044666802132976)],
 ['gittins_bb', (0.007737945727551424, 23.1, 27.427905497868405)],
 ['gittins_bb_delta', (0.5962530712266272, -3.9, 23.278530881479615)],
 ['softmax_ucb', (0.0001271960961194171, 26.0, 21.45693361130616)],
 ['multiarmed_bandit_agent', (0.17846353458821285, 13.4, 31.493491391079523)],
 ['upper_confidence', (5.82610972839857e-17, 114.2, 43.15275194005592)],
 ['ucb_decay', (0.5051202363556915, 7.0, 33.214454684670045)],
 ['bayesian_ucb', (0.0018612734514125444, -23.0, 23.375200533899168)],
 ['thompson', (0.10523248484614844, -11.8, 23.03388807822075)],
 ['neural', (0.3706954653292832, -9.5, 33.559648389

In [ ]:
a = Agent(text=utils.bandits.exact_gittins_with_my_and_count_rival_drift.format("decay=0.03"))
init_agent(a)
a.file

bench(a)

In [20]:
a = Agent(text=utils.bandits.exact_gittins_with_my_and_count_rival_drift.format("decay,rival_drift=0.03,-0.001"))
init_agent(a)
print(a.file)

bench(a)

tmp/b_0.6698981319746636.py
['gittins', (0.0070556045568421835, 23.7, 27.817440572417873)]
['gittins_with_random', (0.04412062421763874, 27.1, 42.57334847061011)]
['gittins_with_count_my', (0.25099289960537385, -9.7, 26.720965551416736)]
['gittins_with_count_rival_drift', (0.04259029267837131, 25.7, 40.08004491015448)]
['gittins_with_my_and_count_rival_drift', (0.5166336434853575, -3.4, 16.578299068360423)]
['gittins_bb', (0.5320094981546408, -4.7, 23.782556632961054)]
['gittins_bb_delta', (0.002768822035859739, -19.3, 20.39632319806685)]
['softmax_ucb', (0.04150945267886, 19.7, 30.56157718443209)]
['multiarmed_bandit_agent', (0.17437960669542285, -12.4, 28.86936092122581)]
['upper_confidence', (3.467615329731626e-31, 108.4, 29.513386793114748)]
['ucb_decay', (0.0005200056109070572, 14.1, 12.848735346328837)]
['bayesian_ucb', (0.009494949012238142, -27.1, 33.04073243740217)]
['thompson', (0.005615350124280827, -24.0, 27.40437921208944)]
['neural', (0.0024994871875276574, -23.9, 24.9977

[['gittins', (0.0070556045568421835, 23.7, 27.817440572417873)],
 ['gittins_with_random', (0.04412062421763874, 27.1, 42.57334847061011)],
 ['gittins_with_count_my', (0.25099289960537385, -9.7, 26.720965551416736)],
 ['gittins_with_count_rival_drift',
  (0.04259029267837131, 25.7, 40.08004491015448)],
 ['gittins_with_my_and_count_rival_drift',
  (0.5166336434853575, -3.4, 16.578299068360423)],
 ['gittins_bb', (0.5320094981546408, -4.7, 23.782556632961054)],
 ['gittins_bb_delta', (0.002768822035859739, -19.3, 20.39632319806685)],
 ['softmax_ucb', (0.04150945267886, 19.7, 30.56157718443209)],
 ['multiarmed_bandit_agent', (0.17437960669542285, -12.4, 28.86936092122581)],
 ['upper_confidence', (3.467615329731626e-31, 108.4, 29.513386793114748)],
 ['ucb_decay', (0.0005200056109070572, 14.1, 12.848735346328837)],
 ['bayesian_ucb', (0.009494949012238142, -27.1, 33.04073243740217)],
 ['thompson', (0.005615350124280827, -24.0, 27.40437921208944)],
 ['neural', (0.0024994871875276574, -23.9, 24.9

In [44]:
compare(
    Agent(file='/Users/sergmiller/Documents/my/bandits/kernels/thompson.py'),
    Agent(text=neural),
    T=20
)

(0.9332597025183905,
 -0.5,
 26.701123571864912,
 array([604., 633., 672., 631., 641., 651., 570., 580., 654., 644., 552.,
        646., 705., 635., 699., 582., 591., 599., 600., 614.]),
 array([650., 653., 675., 646., 576., 636., 572., 591., 646., 649., 594.,
        619., 673., 632., 713., 632., 578., 588., 583., 607.]))

In [47]:
a = Agent(text=utils.bandits.neural_with_new_feature)
init_agent(a)
print(a.file)

compare(
    a,
    Agent(text=neural),
    T=10
)

tmp/b_0.23472610887543255.py


(0.3305564893681603,
 10.3,
 33.47551343893025,
 array([673., 612., 620., 627., 619., 636., 621., 652., 700., 603.]),
 array([662., 649., 576., 633., 640., 585., 605., 601., 665., 644.]))

In [48]:
bench(a)

['gittins', (1.6938640196923583e-10, 40.9, 20.25067900096192)]
['gittins_with_random', (0.052672869607180664, 26.3, 42.923303693914335)]
['gittins_with_count_my', (0.03200258150073675, 12.9, 19.02340663498523)]
['gittins_with_count_rival_drift', (6.017970810148189e-06, 30.0, 20.961870145576228)]
['gittins_with_my_and_count_rival_drift', (0.0008999073004778537, 23.1, 22.002045359466017)]
['gittins_bb', (0.40613713755483416, 5.6, 21.317598363793234)]
['gittins_bb_delta', (0.9581997736625133, 0.5, 30.16703498854337)]
['softmax_ucb', (1.0467690209347524e-05, 31.9, 22.88864347225497)]
['multiarmed_bandit_agent', (0.0709880063216172, 16.8, 29.42379989056478)]
['upper_confidence', (1.9599021635144304e-179, 145.7, 16.131026005806326)]
['ucb_decay', (0.00020299463049364502, 29.1, 24.768730286391346)]
['bayesian_ucb', (0.2935579760577147, -6.6, 19.87058126980688)]
['thompson', (0.8865350313680469, 1.1, 24.37806390999909)]
['neural', (0.3520256594239479, -5.5, 18.688231591030757)]
<string>:82: Ru

[['gittins', (1.6938640196923583e-10, 40.9, 20.25067900096192)],
 ['gittins_with_random', (0.052672869607180664, 26.3, 42.923303693914335)],
 ['gittins_with_count_my', (0.03200258150073675, 12.9, 19.02340663498523)],
 ['gittins_with_count_rival_drift',
  (6.017970810148189e-06, 30.0, 20.961870145576228)],
 ['gittins_with_my_and_count_rival_drift',
  (0.0008999073004778537, 23.1, 22.002045359466017)],
 ['gittins_bb', (0.40613713755483416, 5.6, 21.317598363793234)],
 ['gittins_bb_delta', (0.9581997736625133, 0.5, 30.16703498854337)],
 ['softmax_ucb', (1.0467690209347524e-05, 31.9, 22.88864347225497)],
 ['multiarmed_bandit_agent', (0.0709880063216172, 16.8, 29.42379989056478)],
 ['upper_confidence', (1.9599021635144304e-179, 145.7, 16.131026005806326)],
 ['ucb_decay', (0.00020299463049364502, 29.1, 24.768730286391346)],
 ['bayesian_ucb', (0.2935579760577147, -6.6, 19.87058126980688)],
 ['thompson', (0.8865350313680469, 1.1, 24.37806390999909)],
 ['neural', (0.3520256594239479, -5.5, 18.68